/* while the user input is not equal to the number generated by the computer, if the guess is to high return .... if to low return ...
else return ....*/

let button = document.getElementById("btn");
let computerNum = document.getElementById("computer-number");
let winner = document.getElementsByClassName("winner");
let randomNum = Math.floor(Math.random() * 100);
let success = document.getElementById("nice");



button.addEventListener("click", () => {
    let guessRemaining = 5;
    let tooBig = document.getElementById("too-big");
    let tooSmall = document.getElementById("too-small");
    let userNumber = document.getElementById("userNum").value;

    
    if(userNumber == ""){
        alert("please enter a number");
        guessRemaining -= 1;
    }else if (userNumber > randomNum){
        tooBig.innerHTML = "Too Big";
        setTimeout(function(){
            tooBig.innerHTML = '';
        }, 2000);
        guessRemaining -= 1;
    }else if (userNumber < randomNum){
        tooSmall.innerHTML = "Too Small";
        setTimeout(function(){
            tooSmall.innerHTML = '';
        }, 2000);
        guessRemaining -= 1;
    }else if(userNumber == randomNum){
        success.innerHTML = "Nice Job";
        setTimeout(function(){
            success.innerHTML = '';
            document.location.reload(true);
        }, 2000);

        
    }
    computerNum.innerText = " " + guessRemaining;
})





